# This file lists variables used in configuring dc1 evaluation 
################################################################
##  WASABI credentials
define: &WASABI_KEY "EG5GYSEYI5C20O6IHNEJ"
define: &WASABI_SECRET_KEY "UsYKO5KBda34z2SomwjdI4aKKWSG3jzZ4KP45oOr"


################################################################

glonet_n_days_forecast: 10

max_samples: 2
###########################################
## List of start time for TC events
start_times:
   - "2000-01-01"
## List of end time for TC events 
end_times:
   - "2025-01-01"

# lead time definition (hours)
lead_time_start: "0"
lead_time_stop: "240"
lead_time_frequency: "24"

# variables for evaluation data targets
target_vars: # standard names
  - "uo"
  - "vo"
  - "zos"
  - "thetao"
  - "so"

# SST, SSH, SSSS, U, V
  
#vents 	de surface (sortie) / observations satellitaires (SAR) du vent à haute résolution (référence)
#variables représentatives des vagues de surface (haute résolution) : 	SSH, SST, SSS, couleur de l’océan (sortie) / observations satellite et réanalyses (modèles ERA-5 et Mercator-GLORYS)	(référence)
#distribution de la salinité et de la température de la couche supérieure de l'océan (sortie du modèle) / profils ARGO et réanalyses (modèle Mercator-GLORYS) (référence)


# variables for evaluation data inputs
input_vars: "*"
#variables (SSH, vents de surface, vagues, précipitations, température 	intérieure et de surface, couleur de l’océan) avant, pendant, 	après le passage du cyclone.
#conditions de la haute mer avant la tempête (par exemple, SST, SSS, densité 	verticale de la haute mer, force de stratification, etc.)
#forçages atmosphériques pendant le passage du cyclone (vent maximum, pluie accumulée et 	évaporation, indice de puissance éolienne, etc..)
#sillages océaniques laissés après la tempête pour un ensemble de variables (SST, SSS, hauteur du niveau de la mer, paramètres de couleur de l'océan).
#réanalyses : atmosphérique, océanique, des caractéristiques du vortex.

# Target region coordinates
min_lat: -90
max_lat: 90
min_lon: -180
max_lon: 180

# Path to catalog file
catalog_path: ""

# Datasets
batch_size: 8

std_names_eval_vars:
  - sea_surface_height_above_reference_ellipsoid
  - "U"
  - "V"
  - "sea_surface_height_above_sea_level"
  - "sea_surface_foundation_temperature"

sources:
  - dataset: swot
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC2/Nadir_altimetry/Swot"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/*.nc"
    keep_variables:
      - "time"
      - "latitude"
      - "longitude"
      - "ssha_filtered"
      - "ssha_unfiltered"
      - "i_num_line"
      - "i_num_pixel"
    eval_variables:
      - "ssha_filtered"

  - dataset: argo_velocities
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC2/Argo_velocities"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/*.nc"
    keep_variables:
    - "latitude" 
    - "longitude"
    - "depth"
    - "n_points"
    - "U"
    - "V"
    - "ID"
    eval_variables:
      - "U"
      - "V"
  
  - dataset: argo_profiles
    config: "argopy"
    connection_type: 
    url: 
    file_pattern: "**/*.nc"
    keep_variables:
      - "latitude"
      - "longitude"
      - "depth"
      - "n_points"
      - "ID"
      - "profile_date"
      - "temperature"
      - "salinity"
    eval_variables:
      - "temperature"
      - "salinity"

  - dataset: jason3
    groups:
      - "ku"
      - "data_01"
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC2/Nadir_altimetry/Jason-3"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/*.nc"
    keep_variables:
      - "time"
      - "data_01__time_tai"
      - "latitude"
      - "longitude"
      - "data_01__depth_or_elevation"
      - "data_01__ku__ssha"
      - "data_01__ku__ssha_mle3"
    eval_variables:
      - "data_01__ku__ssha"
      - "data_01__ku__ssha_mle3"

  - dataset: saral
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC2/Nadir_altimetry/Saral"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/*.nc"
    keep_variables:
    - "time"
    - "lat"
    - "lon"
    - "alt"
    - "wind_speed_alt"
    - "ssha"
    - "bathymetry"
    eval_variables:
    - "ssha"

  - dataset: SST_fields
    config: "cmems"
    connection_type:
    cmems_product_name: "cmems_obs-sst_glo_phy_l3s_pir_P1D-m"
    file_pattern: "**/*.nc"
    keep_variables:
    - "crs"
    - "sea_surface_temperature"
    - "or_number_of_pixels"
    - "sea_surface_temperature_stddev"
    - "quality_level"
    - "adjusted_sea_surface_temperature"
    eval_variables:
    - "sea_surface_temperature"
    - "adjusted_sea_surface_temperature"

  - dataset: jason1
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC2/Nadir_altimetry/Jason-1"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/*.nc"
    keep_variables:
    - "time"
    - "lat"
    - "lon" 
    - "alt"
    - "mean_sea_surface"
    - "mean_topography"
    - "bathymetry"
    - "wind_speed_alt"
    - "ssha"
    eval_variables:
    - "ssha"

  - dataset: jason2
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC2/Nadir_altimetry/Jason-2"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/*.nc"
    keep_variables:
    - "time"
    - "lat"
    - "lon" 
    - "surface_type"
    - "alt"
    - "mean_sea_surface"
    - "mean_topography"
    - "bathymetry"
    - "wind_speed_alt"
    - "wind_speed_alt_mle3"
    - "ssha"
    - "ssha_mle3"
    eval_variables:
    - "ssha"
    - "ssha_mle3"

  - dataset: SSS_fields
    groups:
      - "ku"
      - "data_01"
    config: "s3"
    connection_type: "wasabi"
    url: "https://s3.eu-west-2.wasabisys.com"
    s3_bucket: "ppr-ocean-climat"
    s3_folder: "DC2/Nadir_altimetry/Jason-3"
    s3_key: *WASABI_KEY
    s3_secret_key: *WASABI_SECRET_KEY
    file_pattern: "**/*.nc"
    keep_variables:
    'time':
    - "time"
    - "data_01__time_tai"
    - "latitude"
    - "longitude"
    - "data_01__altitude"
    - "data_01__mean_sea_surface_cnescls"
    - "data_01__wind_speed_alt"
    - "data_01__wind_speed_alt_mle3"
    - "data_01__ku__ssha"
    - "data_01__ku__ssha_mle3"
    eval_variables:
    - "data_01__ku__ssha"
    - "data_01__ku__ssha_mle3"